export const categories = [
  "Branded Cut Pieces",
  "Men's Wear",
  "Women's Wear",
  "Dresses",
  "Handbags",
  "Accessories",
  "Cosmetics",
];

export const products = [
  {
    id: 1,
    name: "Elegant Embroidered Dress",
    category: "Dresses",
    price: 4500,
    image: "https://lrggyvioreorxttbasgi.supabase.co/storage/v1/object/public/app-assets/22326/images/1780821097669-product-dress-1",
    description: "Beautiful embroidered dress perfect for special occasions",
    isNew: true,
    isBestSeller: false,
  },
  {
    id: 2,
    name: "Premium Branded Cut Piece",
    category: "Branded Cut Pieces",
    price: 3200,
    image: "https://lrggyvioreorxttbasgi.supabase.co/storage/v1/object/public/app-assets/22326/images/1780821103641-product-fabric-1",
    description: "High quality branded cut piece fabric",
    isNew: false,
    isBestSeller: true,
  },
  {
    id: 3,
    name: "Men's Premium Kurta Set",
    category: "Men's Wear",
    price: 3800,
    image: "https://lrggyvioreorxttbasgi.supabase.co/storage/v1/object/public/app-assets/22326/images/1780821099489-product-mens-1",
    description: "Stylish men's kurta set for formal and casual wear",
    isNew: true,
    isBestSeller: false,
  },
  {
    id: 4,
    name: "Designer Leather Handbag",
    category: "Handbags",
    price: 5500,
    image: "https://lrggyvioreorxttbasgi.supabase.co/storage/v1/object/public/app-assets/22326/images/1780821102698-product-bag-1",
    description: "Premium designer handbag for everyday elegance",
    isNew: false,
    isBestSeller: true,
  },
  {
    id: 5,
    name: "Luxury Cosmetics Set",
    category: "Cosmetics",
    price: 2800,
    image: "https://lrggyvioreorxttbasgi.supabase.co/storage/v1/object/public/app-assets/22326/images/1780821105508-product-cosmetics",
    description: "Complete cosmetics collection for the modern woman",
    isNew: true,
    isBestSeller: false,
  },
  {
    id: 6,
    name: "Fashion Accessories Bundle",
    category: "Accessories",
    price: 1900,
    image: "https://lrggyvioreorxttbasgi.supabase.co/storage/v1/object/public/app-assets/22326/images/1780821106525-product-accessories",
    description: "Trendy accessories to complete your look",
    isNew: false,
    isBestSeller: true,
  },
  {
    id: 7,
    name: "Classic Women's Suit",
    category: "Women's Wear",
    price: 5200,
    image: "https://lrggyvioreorxttbasgi.supabase.co/storage/v1/object/public/app-assets/22326/images/1780821097669-product-dress-1",
    description: "Elegant women's suit with intricate detailing",
    isNew: true,
    isBestSeller: false,
  },
  {
    id: 8,
    name: "Men's Casual Collection",
    category: "Men's Wear",
    price: 3500,
    image: "https://lrggyvioreorxttbasgi.supabase.co/storage/v1/object/public/app-assets/22326/images/1780821099489-product-mens-1",
    description: "Comfortable and stylish casual wear for men",
    isNew: false,
    isBestSeller: false,
  },
];
